### ISSUE TITLE
What is the interval of taking snapshots? What not just before going to sleep?

### ISSUE THREAD

**Issue by pstein** [Crozzers/RestoreWindowPos#1]
It is said, that RWP takes occasionally snapshots of the current windows positions.

What is th frequency?
Every 2 seconds?
How can change the frequency?

However this is resource consuming.

Why not change the snapshot trigger to "5 seconds before timeout/going computer to sleep"?

**Comment by Crozzers** [comment]
Yes, RestoreWindowPos takes regular snapshots of window positions, by default every minute. You can change the snapshot frequency by right clicking the system tray icon, which looks [like this](https://raw.githubusercontent.com/Crozzers/RestoreWindowPos/main/assets/icon256.ico). Once the menu has appeared you can hover over the "Snapshot frequency" submenu and select your desired frequency from there.
![image](https://user-images.githubusercontent.com/57498990/219939339-dceecc4f-54fa-40a4-9bc4-78a1be10cc3a.png)
The above image is a screenshot from RestoreWindowPos v0.8.2.

> Why not change the snapshot trigger to "5 seconds before timeout/going computer to sleep"?

I would much prefer this approach, but from my testing I could not find a reliable way to detect when the computer is about to go to sleep.

**Comment by Crozzers** [comment]
Hi there! I have since discovered the `PBT_APMSUSPEND` event which, according to Microsoft documentation:
> Notifies applications that the computer is about to enter a suspended state

I have added the ability to capture snapshots when this event fires, right before the computer goes to sleep (fc99e4f) and intend to release this as part of v0.9.0.

Unfortunately, it is still necessary to regularly take snapshots since there is not an equivalent event for when a display is disconnected, which can happen at any time.
